---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1606597/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp changelog.txt $DEPLOYPATH
    - /bin/cp -r assets $DEPLOYPATH
    - /bin/cp -r forms $DEPLOYPATH